### ISSUE TITLE
Does it support LuaJit bytecode?

### ISSUE THREAD

**Issue by brandonros** [CPunch/LuaPytecode#1]
Example hex header:

```
1B4C4A0102DA0100020D0008
```

If not, what would it take to support this old (v1 of LJBC format from 2.0.5 instead of v2 from 2.1.0-beta)?

**Comment by CPunch** [comment]
unfortunately the current implementation is not very well suited to parse multiple versions of lua bytecode, and only supports vanilla 5.1 bytecode.

but! there is a project which does have support for deserializing [LJBC](https://github.com/NightNord/ljd/tree/master/ljd)

it would be neat to be able to support multiple versions in the future though :yum:
